### ISSUE TITLE
Running all micro services as monolithic

### ISSUE THREAD

**Issue by joaopenas** [ashleydavis/sharing-typescript-code-libraries#1]
Hello, first thing first, thanks for sharing this ideia and structure, i think is perfectly.

I already recreate your examples, and i put working local and in a docker container.

I face two issues and I will explain. (Maybe the issues it's something that i don't know ^^)

I have this project structure as an example: 
![Image1](https://user-images.githubusercontent.com/12494588/154157310-b0e720c5-aa07-4a14-976b-d3be0163a125.PNG)

-The base folder contains express server and a internal function using lodash just returning one reverse array.
-The microservice-a references base microservice throw tsconfig, where earn express server, contains his own route and one function just return a send response.

The first issue is..
To deploy microservice-a in a docker container was necessary changed dockerfile to run "npm install" in base folder before run "npm build" on microservice-a.

![Image2](https://user-images.githubusercontent.com/12494588/154160679-b8cb2702-2111-4804-9566-19e8cbc2bf49.PNG)

Do you have any idea if i can improve this procedure or i'm doing something wrong?
Based on that if i have more 5 libs, it's necessary run "npm install" in every lib before run "npm build"?

The second one is...
When i want run all micro services together in my dev environment i need create a package.json and tsconfig.json with all dependecies in every microservice and install locally.

It's necessary also remove src folder in every microservice, because when i run "tsc --build" in all project, the dist folder includes src folder, and then relative path will not working well.

Do you have any idea to resolve this?
I can keep src folder and maybe in build step remove it?

Thanks in advance.

**Comment by ashleydavis** [comment]
I'm sorry but I'm not sure how to help you. I'm having a lot of trouble understanding what you are trying to achieve.

Looking at your project structure it seems you have the project for microservice-a embedded in another project, where as it should probably be a TypeScript project on its own. I don't think I have any examples with nested TypeScript projects (is that really what you want to do)? It might be possible, but I'm not sure how to do it.

If you are looking at the microservices example, it's not designed to be run as monolithic. So if you are trying to do that, it's probably not going to work for you.

I might be able to help if you can show me some example code for your project.

Feel free to send me a Git repo with example code. You can DM me on Twitter @codecapers to chat about it.
