### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by stt106** [ashleydavis/sharing-typescript-code-libraries#2]
Hi,

Thanks for sharing this. This is exactly what I am after as we have many common types between client and server; we used to duplicate each type.

My file structure is like this:
-MyApp
--client
----tsconfig.js
----src
--common
----dist
----src
------file1.ts
------file2.ts
----tsconfig.json
--server
----src
----dist
----tsconfig.json

I followed your setting exactly as it is in each `tsconfig..json`; typescript files compile fine but when running my server (express); I got "Cannot find module `../../../common/src/file1`.
But if I remove the `dist` folder under `common` then it works; but this is not ideal as all the xxx.d.ts and xxx.js files are in `src` folder. Any idea what I am doing wrong and how to fix it?
Thanks again for sharing.

**Comment by ashleydavis** [comment]
Hi, I can't really help you debug your code unless you give me access to it.

Please feel free to send me a zip file (ashley@codecapers.com.au) or a link to a git repo that contains the broken code.
