### ISSUE TITLE
Docker build doesnt work when a library imports a dependency

### ISSUE THREAD

**Issue by ilijaNL** [ashleydavis/sharing-typescript-code-libraries#3]
Hello, great tutorial, however there is a big problem. When using an dependency in one of the libs, the docker build fails inside the the backend.

Change content of the libs/my-library/src/index.ts to

```typescript
import dayjs  from "dayjs";
export function showMessage(): string {
    return "Hello world!\n" + dayjs.unix(0).toISOString();   
}
```

**Comment by ashleydavis** [comment]
I thanks for reporting the issue, but I don't understand what it has to do with Docker?

Can you share the command you were using to Build and the error message you were getting?

**Comment by ilijaNL** [comment]
Go to https://github.com/ashleydavis/sharing-typescript-code-libraries/blob/0ee7746438f6403b6901aef5354d983455305972/microservices-and-frontend-example/libs/my-library/src/index.ts#L1 and import the dayjs dependency. Try to build the backend docker image. The typescript compiler will say that it doesn't recognize the dayjs dependency, since it is never installed inside the my-library directory

**Comment by ashleydavis** [comment]
The Docker file does contain commands to install dependencies for all the libraries and dayjs is a dependency so it should work.

But I'm not sure how you are running it. What command are you using to build it? What directory are you in when you build it? What is the output from your terminal?

I might be able to help, but I need details.

**Comment by ilijaNL** [comment]
> The Docker file does contain commands to install dependencies for all the libraries and dayjs is a dependency so it should work.
> 
> But I'm not sure how you are running it. What command are you using to build it? What directory are you in when you build it? What is the output from your terminal?
> 
> I might be able to help, but I need details.

No it doesn't, only after npm run build (https://github.com/ashleydavis/sharing-typescript-code-libraries/blob/0ee7746438f6403b6901aef5354d983455305972/microservices-and-frontend-example/backend/my-project/Dockerfile#L26) which will fail since no "my-libs" dependencies are installed and thus typescript build cannot succeed (it works in this repo, because no external dependencies are imported in my-lib sources). A possible solution is to recursively install all dependencies in the root context.

Ps I am just cloning the repository, cd into the microservices-and-frontend-example/backend/my-project and running the docker build command from the readme. This will indeed succeed. Now if you go to my-lib directory and import an external dependency inside the index.ts (also use it), it will fail the backend/my-project docker build at the npm run build step

**Comment by ashleydavis** [comment]
I just built it according to the instructions in the [README](https://github.com/ashleydavis/sharing-typescript-code-libraries/tree/main/microservices-and-frontend-example) and it builds without errors.

Here's the commands:

```bash
cd sharing-typescript-code-libraries/microservices-and-frontend-example/backend/my-project
docker build ../.. -f ./Dockerfile -t hello-world
```

Just to prove that it builds, I'll share my build log with you. I created the build log using the command like this:

```bash
docker build ../.. -f ./Dockerfile -t hello-world --no-cache --progress=plain 2>&1 | tee run.log
```

Please take a look at the build log and you'll see where the command `npm-recursive-install`  is invoked that installs all dependencies recursively:

[build.log](https://github.com/ashleydavis/sharing-typescript-code-libraries/files/9422654/build.log)

Again, I'm still happy to help, but you aren't providing me enough details for me to help you solve your problem.

Also please read my blog post on this code before you come back to me again, that might help you figure somethings out:

https://www.codecapers.com.au/sharing-typescript-code-between-projects/

**Comment by ilijaNL** [comment]
I think there is misunderstanding here about installing dependencies. The installation happens after you run the build (which invokes tsc --build), however you need those my-lib dependencies already installed to run the build...

See my clone and the last commit: https://github.com/ilijaNL/sharing-typescript-code-libraries/commit/f9e4ffd24b12d25630d5e34de72f8d96c46e0c0d

You can clone it, and follow your readme inside https://github.com/ilijaNL/sharing-typescript-code-libraries/tree/main/microservices-example

```
cd my-project
docker build .. -f ./Dockerfile -t hello-world
```

The following error is given:

```
 => ERROR [builder 6/9] RUN npm run build                                                                                                                                                                   2.3s 
------
 > [builder 6/9] RUN npm run build:
#11 1.090
#11 1.090 > main@1.0.0 build /usr/src/my-project
#11 1.090 > tsc --build && ts-project-bundle --out=build
#11 1.090
#11 2.208 ../libs/my-library/src/index.ts(1,20): error TS2307: Cannot find module 'dayjs' or its corresponding type declarations.
#11 2.225 npm ERR! code ELIFECYCLE
#11 2.225 npm ERR! errno 1
#11 2.232 npm ERR! main@1.0.0 build: `tsc --build && ts-project-bundle --out=build`
#11 2.232 npm ERR! Exit status 1
#11 2.233 npm ERR!
#11 2.233 npm ERR! Failed at the main@1.0.0 build script.
#11 2.233 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#11 2.240
#11 2.240 npm ERR! A complete log of this run can be found in:
#11 2.240 npm ERR!     /root/.npm/_logs/2022-08-25T08_38_58_599Z-debug.log
```

**Comment by ashleydavis** [comment]
It looks like you are setting your context wrong.

Note the context when I run the build:

```bash
cd sharing-typescript-code-libraries/microservices-and-frontend-example/backend/my-project
docker build ../.. -f ./Dockerfile -t hello-world
```

You set the context to `..` in your build command, in mine I have set it to `../..`.

**Comment by ilijaNL** [comment]
> It looks like you are setting your context wrong.
> 
> Note the context when I run the build:
> 
> ```shell
> cd sharing-typescript-code-libraries/microservices-and-frontend-example/backend/my-project
> docker build ../.. -f ./Dockerfile -t hello-world
> ```
> 
> You set the context to `..` in your build command, in mine I have set it to `../..`.

You using microservices-and-frontend-example, I use microservices-example, which has my-project one lever higher...

You can just clone my fork of your repo:

```
cd microservices-example
# from the readme inside microservices-example
cd my-project
docker build .. -f ./Dockerfile -t hello-world
```

**Comment by ashleydavis** [comment]
This is why details help, you referenced the frontend example in one of your earlier comments.

I'll take a look again when I have a moment.

**Comment by kasparas12** [comment]
@ashleydavis I had to alter Dockerfile
to npm install dependencies in shared library in order
for container to start working. You can observe the error otherwise, for instance, when using process.env.*** in shared code to print some environment variable. if @types/node is not installed then docker will fail. tsc -b seems not to be doing npm install for referenced projects

**Comment by ashleydavis** [comment]
Ok cool. Thanks for letting me know. Are you able to submit a pull request so I can see the change you made?

**Comment by Hannnes1** [comment]
I realize that this is an old issue, but the simplest solution is to just run `npm install` for all references before `npm run build`. In this case, the following should be added:

```
WORKDIR /usr/src/libs/my-library
RUN npm install # Or `npm ci`
```

It would be nice if there was a command to install dependencies of all references in one go,  but I haven't found anything that works.

**Comment by SergiyIva** [comment]
I'm also try to resolve that problem, but didn't find any good solutions.  One of the variants is to use workspaces for share node_modules between projects.

**Comment by ashleydavis** [comment]
These days I tend to use pnpm for sharing packages between applications in a mono repo. 

I have an example of that here for anyone interested:
https://github.com/ashleydavis/pnpm-workspace-examples
