### ISSUE TITLE
Do you need to npm install in shared libraries

### ISSUE THREAD

**Issue by kaykhan** [ashleydavis/sharing-typescript-code-libraries#4]
One question i have with using references, do you need to run npm install in the shared library folder. 

i have achieved the same as you except without using references, instead i use paths.

tsconfig

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@core/*": [
                "../core/src/*"
            ],
            "@config": [
                "src/config.ts"
            ],
        }
    }
}
```

`core` is my shard library, but it requires me to do npm install within core first. otherwise i get a bunch of errors:

```
../core/src/config.ts:1:19: ERROR: Could not resolve "dotenv"
../core/src/modules/http.module.ts:1:15: ERROR: Could not resolve "qs"
../core/src/modules/http.module.ts:2:18: ERROR: Could not resolve "axios"
../core/src/modules/logger.module.ts:1:46: ERROR: Could not resolve "winston"
```

So i tried changing this pattern to use references like urs...

```
    "references": [
        {
            "path": "../../core"
        }
    ]
```

but i still have to do an npm install, i guess im trying to work out what the differnece is, if there is any and if npm install is required to be ran in shared lib

**Comment by ashleydavis** [comment]
"npm install" isn't required to share TypeScript projects within mono repo. It is only needed when you install packages from the npm registry.

These days I'm using pnpm workspaces to share packages within a mono repo and it works really well. You might want to try it out: https://www.codecapers.com.au/pnpm-workspaces/
